<?php

namespace ArtspaceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DetailcommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetailcommandeRepository extends EntityRepository
{
}
