artspace_homepage:
    path:     /
    defaults: { _controller: ArtspaceBundle:Pricing:ShowArtspace }
artspace_categories:
    path:     /pricing/{categorie}
    defaults: { _controller: ArtspaceBundle:Pricing:ShowCategorie, categorie:standard }
artspace_detail:
    path:   pricing/detail/{id}
    defaults: { _controller: ArtspaceBundle:Pricing:ShowDetail }
artspace_register:
    path:     /register
    defaults: { _controller: ArtspaceBundle:User:register }
artspace_login:
    path:     /login
    defaults: { _controller: ArtspaceBundle:User:login }
artspace_login_check:
    path:     /login_check
    defaults: { _controller: ArtspaceBundle:User:loginCheck }
artspace_logout:
    path:     /logout
    defaults: { _controller: ArtspaceBundle:User:logout }
