artspace_homepage:
    path:     /
    defaults: { _controller: ArtspaceBundle:Pricing:ShowArtspace }
artspace_categories:
    path:     /pricing/{categorie}
    defaults: { _controller: ArtspaceBundle:Pricing:ShowCategorie, categorie:standard }
artspace_detail:
    path:   pricing/detail/{id}
    defaults: { _controller: ArtspaceBundle:Pricing:ShowDetail }
register:
    path:     /register
    defaults: { _controller: ArtspaceBundle:User:register }
view_cart:
    path:     /cart
    defaults: { _controller: ArtspaceBundle:Cart:viewCart }
ajout_panier:
    path:     /ajout-panier
    defaults: { _controller: ArtspaceBundle:Cart:ajoutPanier }
suppr_panier:
    path:     /suppr-panier
    defaults: { _controller: ArtspaceBundle:Cart:supprPanier }
panier:
    path:     /panier
    defaults: { _controller: ArtspaceBundle:Panier:viewPanier }
add_panier:
    path: /panier/add/{id}
    defaults: { _controller: ArtspaceBundle:Panier:addToPanier }
delete_panier:
    path: /panier/delete/{id}
    defaults: { _controller: ArtspaceBundle:Panier:deletePanier }
delete_product:
    path: /pricing/delete/{id}
    defaults: { _controller: ArtspaceBundle:Pricing:deleteProduct }
backoffice_show:
    path: /admin
    defaults: { _controller: ArtspaceBundle:Pricing:showAdmin }
commande:
    path: /commande
    defaults: { _controller: ArtspaceBundle:Commande:commandeSave }
commande_recapitulatif:
    path: /recap
    defaults: { _controller: ArtspaceBundle:Commande:commandeView }
    
backoffice_create:
    path: /newproduct
    defaults: { _controller: ArtspaceBundle:Pricing:create }
    
    
#back_delete:
#    path:     /admin/delete/{id}
#    defaults: { _controller: ArtspaceBundle:Pricing:delete }
