artspace:
    resource: "@ArtspaceBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation

login:
    path:     /login
    defaults: { _controller: ArtspaceBundle:User:login }
login_check:
    path:     /login_check
    defaults: { _controller: ArtspaceBundle:User:loginCheck }
logout:
    path:     /logout
    defaults: { _controller: ArtspaceBundle:User:logout }