security:
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  /login
                check_path:  /login_check
            logout:
                path:   /logout
                target: /

    providers:
        users:
            entity: { class: ArtspaceBundle:User, property: username }

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/panier, roles: ROLE_USER }
        - { path: ^/user, roles: ROLE_USER }

    encoders:
        ArtspaceBundle\Entity\User:
            algorithm: sha512